In [1]:
from __future__ import print_function
import torch

In [2]:
import numpy as np

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[3.9236e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2327, 0.4084, 0.8277],
        [0.2464, 0.6771, 0.6384],
        [0.8097, 0.2461, 0.4183],
        [0.9382, 0.6515, 0.2033],
        [0.0205, 0.2309, 0.5834]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.9322, 0.6879, 0.4531],
        [0.2817, 0.5825, 0.0971],
        [0.6418, 0.7475, 0.9717],
        [0.1096, 0.3804, 0.1816],
        [0.4038, 0.9808, 0.5712]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
y = torch.rand(5, 3)

In [11]:
print(x + y)

tensor([[1.8834, 0.6880, 0.9152],
        [0.4276, 1.1370, 1.0411],
        [0.8318, 1.1045, 1.1826],
        [0.4166, 0.7394, 0.5291],
        [0.6542, 1.0730, 1.5553]])


In [12]:
torch.add(x, y)

tensor([[1.8834, 0.6880, 0.9152],
        [0.4276, 1.1370, 1.0411],
        [0.8318, 1.1045, 1.1826],
        [0.4166, 0.7394, 0.5291],
        [0.6542, 1.0730, 1.5553]])

In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.8834, 0.6880, 0.9152],
        [0.4276, 1.1370, 1.0411],
        [0.8318, 1.1045, 1.1826],
        [0.4166, 0.7394, 0.5291],
        [0.6542, 1.0730, 1.5553]])


In [14]:
y.add_(x)
print(y)

tensor([[1.8834, 0.6880, 0.9152],
        [0.4276, 1.1370, 1.0411],
        [0.8318, 1.1045, 1.1826],
        [0.4166, 0.7394, 0.5291],
        [0.6542, 1.0730, 1.5553]])


In [15]:
print(x[:, 1])

tensor([0.6879, 0.5825, 0.7475, 0.3804, 0.9808])


In [16]:
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.1586])
0.15864819288253784


In [18]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [19]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [20]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [21]:
print(b)

[2. 2. 2. 2. 2.]


In [22]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [23]:
torch.cuda.is_available()

False